name: Publish docs
run-name: Publish docs
on:
  workflow_call:
    
jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pip3 install poetry
      - name: Install dependencies
        shell: bash
        run: poetry install --with doc
      - name: Sphinx build
        run: poetry run sphinx-build docs/source docs/build
      - name: Publish docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          publish_branch: gh-pages