name: Test
run-name: Test
on:
  push:
    branches-ignore:
    - dev*
    - main
    - gh-pages

jobs:
  integration:
    name: Integration testing
    uses: ./.github/workflows/_integration.yml
    with:
      code-quality-may-fail: true
  publish-docs:
    name: Publish docs
    uses: ./.github/workflows/_publish_docs.yml
